[package]
name = "lispers"
description = "lisp interpreter in rust"
publish = false
version = "0.1.0"

edition = "2021"

[lib]
name = "lispers"
path = "src/lib.rs"

[[bin]]
name = "demo"
path = "src/bin/demo.rs"

[[bin]]
name = "repl"
path = "src/bin/repl.rs"

[dependencies]
as-any = "0.3.1"
futures = "0.3.30"
image = "0.25.5"
nalgebra = "0.33.2"
nix = "0.29.0"
