[package]
name = "lispers"
description = "lisp interpreter in rust"
publish = false
version = "0.1.0"

edition = "2021"

[[bin]]
name = "demo"
path = "src/demo.rs"

[[bin]]
name = "repl"
path = "src/repl.rs"

[dependencies]
as-any = "0.3.1"
futures = "0.3.30"
nix = "0.29.0"
